### ISSUE TITLE
DOD: Fabrica Improvements

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#108]
# DOD:  Fabrica Improvements

### Development Checklist (@svogt0511  )
- [x] Passed through peer review see Pull Request Guidelines.  (The code for each task was reviewed by team members on completion of that work.)
- [x] Unit, integration, and system tests that all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed. (Review by other dev team members? Has been reviewed by project members.)
- [X] Confirmed to be working in the stage environment with no new Sentry errors.
- [X] Write an ADR (when relevant). - 1 ADR for the title sort. (Moved to epic 'pre-merge' to do.)
- [X] Confirmed that user stories are met:
  - [X] Feature: Create DOI from any page	
  - [X] Feature: Home Landing page	
  - [X] Feature: New Navigation bar	
  - [X] Feature: Autosuggest input Format	
  - [X] Feature: Export query results metadata	
  - [X] Feature: Fabrica help messages	
  - [X] Feature: DOIs List sorting	
  - [X] Feature: Register DOIs into the future	
  - [X] Feature: Render Latex Formulas correctly	
  - [X] Feature: Add terms to controlled vocabularies	
  - [X] Feature: Remove Profile pages from Fabrica
 - [X] Deployment checklist - see the [epic](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/gh/datacite/datacite/1428)
 - [X] Feature Flag was not used.

### Product Engineering Checklist (@kjgarza )
  - [x] Feature: Create DOI from any page	
  - [x] Feature: Home Landing page	
  - [x] Feature: New Navigation bar	
  - [x] Feature: Autosuggest input Format	
  - [x] Feature: Autosuggest input language	
  - [x] Feature: Export query results metadata	
  - [x] Feature: Fabrica help messages	
  - [x] Feature: DOIs List sorting	
  - [x] Feature: Register DOIs into the future	
  - [x] Feature: Render Latex Formulas correctly	
  - [x] Feature: Add terms to controlled vocabularies	
  - [x] Feature: Remove Profile pages from Fabrica
- [x] Feature Flag has been removed. (where relevant)

**Comment by kjgarza** [comment]
Amazing work @svogt0511 @codycooperross @bklaing2 I think i only found minor issues in 3 features. The details are in: https://bracco-mft35bhdg-datacite.vercel.app/repositories/ethz.ubasojs/dois i added the comments to vercel (if you know how to see them)

![Screenshot 2023-01-16 at 13 24 16](https://user-images.githubusercontent.com/1092861/212677583-e1244fda-59f3-483a-9786-ccd3285efd5d.png)

**Comment by svogt0511** [comment]
@kjgarza and @bklaing2  - Regarding the [vercel comment on formats](https://bracco-mft35bhdg-datacite.vercel.app/repositories/datacite.demo/dois/new#thread-id=xFnZv), I think that for some reason we were confused about what you wanted to see in the Formats dropdown in the create/update dois form.

Sample from the [IANA Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) standard:

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/4681304/212952952-17240d8f-72fb-4202-b24d-c3831abb7307.png">


@kjgarza - Do you want to see the 'Name' value in the dropdown and selection and the 'template' value goes to the database?

I think the template value needs to be in the dropdown because, the name values are not unique.  For example, the 'ogg' format has 3 template values, as shown in the screenshots, below.  I think that precludes us from showing just the name value.

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/4681304/212953615-37989730-8355-4954-82c1-aee1faed0111.png">

<img width="944" alt="image" src="https://user-images.githubusercontent.com/4681304/212953701-a498e0dc-eb64-44d8-9cb7-ef1271b298cc.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/4681304/212953768-38b46f56-d046-4610-991c-12ecc3af3803.png">

**Comment by svogt0511** [comment]
@kjgarza and @codycooperross - Regarding [vercel review comment](https://bracco-mft35bhdg-datacite.vercel.app/dois/10.70102%2Fpz93-sc49#thread-id=vvTuL)

> language doesn't seem to appear in the JSON response, even when it exist in the XML

I thought that this lupo change had been reviewed and merged and was in the staging environment.  Mike just reviewed it and that should be working as soon as the [pull request #893](https://github.com/datacite/lupo/pull/893) is merged in lupo.

We can re-test to resolve this issue as soon as it is merged.  Sorry about that!

**Comment by kjgarza** [comment]
> @kjgarza and @bklaing2  - Regarding the [vercel comment on formats](https://bracco-mft35bhdg-datacite.vercel.app/repositories/datacite.demo/dois/new#thread-id=xFnZv), I think that for some reason we were confused about what you wanted to see in the Formats dropdown in the create/update dois form.
> 
> Sample from the [IANA Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) standard:
> 
> <img width="1333" alt="image" src="https://user-images.githubusercontent.com/4681304/212952952-17240d8f-72fb-4202-b24d-c3831abb7307.png">
> 
> 
> @kjgarza - Do you want to see the 'Name' value in the dropdown and selection and the 'template' value goes to the database?
> 
> I think the template value needs to be in the dropdown because, the name values are not unique.  For example, the 'ogg' format has 3 template values, as shown in the screenshots, below.  I think that precludes us from showing just the name value.
> 
> <img width="1138" alt="image" src="https://user-images.githubusercontent.com/4681304/212953615-37989730-8355-4954-82c1-aee1faed0111.png">
> 
> <img width="944" alt="image" src="https://user-images.githubusercontent.com/4681304/212953701-a498e0dc-eb64-44d8-9cb7-ef1271b298cc.png">
> 
> <img width="788" alt="image" src="https://user-images.githubusercontent.com/4681304/212953768-38b46f56-d046-4610-991c-12ecc3af3803.png">
> 
> 
> 
> 
> 
> 

Ohhh I see what you mean.... I think my original assumption was that the relationship were one to one. Let me think about this.

**Comment by svogt0511** [comment]
@kjgarza - Regarding the [formats power-select dropdown issue](https://bracco-mft35bhdg-datacite.vercel.app/dois/10.12685%2F2x5j-b736/edit#thread-id=HRoMh)

> I think there is an issue with the format of the power-select. you can see you can scroll within the input field. that doesn't happen in any other compoenet (subejcts or languges)

I have fixed that with a style update.  I will let you know when it has been deployed so you can take a look at it.

**Comment by svogt0511** [comment]
@kjgarza - Regarding [the export doi metadata file name issue](https://bracco-mft35bhdg-datacite.vercel.app/repositories/datacite.demo/dois#thread-id=ktlic)

> Could we change the file name to something more descriptive, such as:   today_date + client_id + page_number 

I have modified the file name to what you suggested.  Also, I think I had the button showing on pages that it shouldn't have  (ex, the top level /dois page).  I modified that to show the button only on "repositories.show.dois.index" pages.  I will let you know when it has been deployed so you can look at it.

**Comment by svogt0511** [comment]
@kjgarza - Regarding [changes to the create doi button html](https://bracco-mft35bhdg-datacite.vercel.app/repositories/ethz.ubasojs/dois#thread-id=p0Bvd):

> could we add a ID to the button and the dropdown click elements ('a') to track them.  Something along the lines of omnipresent-new-doi , omnipresent-secondary-new-doi, omnipresent-upload-doi, export-metadata

Prrobably.  I will give it a try to see if it can be done.

**Comment by kjgarza** [comment]
You can see how all other buttons have it already https://github.com/datacite/bracco/blob/391cb7bcb3ff5b7ef712903d3bc710f3bebc160a/app/templates/prefixes/index.hbs#L23

**Comment by svogt0511** [comment]
> You can see how all other buttons have it already https://github.com/datacite/bracco/blob/391cb7bcb3ff5b7ef712903d3bc710f3bebc160a/app/templates/prefixes/index.hbs#L23

So I am assuming that:

- omnipresent-new-doi => the link in the 'create doi button'
- omnipresent-secondary-new-doi => the 'doi form' link in the create doi button dropdown.
- omnipresent-upload-doi => the 'file upload' link in the create doi button dropdown.
- export-metadata => the link in the 'export basic metadata' button

I have added those ids.  The export-metadata button is actually a button and not an <a>.  I added the id to the button.  Hopefully that can be tracked.

**Comment by svogt0511** [comment]
@kjgarza - I think I have addressed all of the review comments.  I will post the vercel link here as soon as a new fabrica has been deployed with the fixes.

Actually, we do need to address the 'formats' question tomorrow, so that one is left to finish.

**Comment by svogt0511** [comment]
@kjgarza - I also changed the version shown on the /about page to "4.0.0".  The second half of this is to remember to use the 4.0.0 release tag when deploying it.

I have deployed all changes from review comments to vercel [here](https://bracco-gnmluikze-datacite.vercel.app/).  Please take a look and let me know if you need anything else.  We should only have the formats issue to finish.

**Comment by kjgarza** [comment]
@svogt0511 everything looks great.
w/r/t Format, I guess the original design from @bklaing2  is the way to go. Unfortunately, I didn't consider the 1-to-many relation of extensions and mime-types. Apologies for all the extra back-and-forth.

then the behavior would be better if goes like this:

1. as in the user searches using the name,
2. they see the mimetypes
3. they select the mimetype
4. the mimestype is displayed

Could I leave that to you to change?, and we can consider verification finished

many thanks :thumbsup:

**Comment by svogt0511** [comment]
@kjgarza - reverted that power-select to the original implementation by @bklaing2.

You can verify that in vercel at: https://bracco-hnrbo0blt-datacite.vercel.app/

Thanks!  We are done!!  Should be time to schedule deployment.

**Comment by svogt0511** [comment]
@kjgarza - Closing this.  You can reopen it if necessary.
