### ISSUE TITLE
DOD: NFDI Instrument

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#110]
# DOD: NFDI Instrument

### Development Checklist
- [x] Passed through peer review see Pull Request Guidelines
- [ ] ~~Unit, integration, and system tests that all pass on the CI.~~
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [x] Confirmed to be working in the stage environment with no new Sentry errors.
- [ ] ~~Write an ADR (when relevant).~~
- [ ] Confirmed that user stories are met:
    1. [x] Feature: Instrument Metadata display	
    2. [x] Feature: Data that used an Instrument	
    3. [x] Feature: Publications that used an Instrument	
    4. [ ] Feature: Instrument connections list and histogram	
    5. [x] Feature: Co-authors List

### Product Engineering Checklist
- [x]  Confirmed that user stories are done:
    1. [x] Feature: Instrument Metadata display	
    2. [x] Feature: Data that used an Instrument	
    3. [x] Feature: Publications that used an Instrument	
    4. [x] Feature: Instrument connections list and histogram	
    5. [x] Feature: Co-authors List
- [x] Feature Flag has been removed. (where relevant)

### Engagement Checklist
- [ ] Documentation has been updated
- [ ] Blogpost/newsletter has been written

**Comment by bklaing2** [comment]
- [x]  Passed through peer review see Pull Request Guidelines
- [ ]  ~Unit, integration, and system tests that all pass on the CI.~
- [x]  Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x]  Reviewed by relevant reviewers and all comments are addressed.
- [ ]  ~Confirmed to be working in the stage environment with no new Sentry errors.~
- [ ]  ~Write an ADR (when relevant).~
- [ ]  Confirmed that user stories are met:
  - [x]  Feature: Instrument Metadata display
  - [x]  Feature: Data that used an Instrument
  - [x]  Feature: Publications that used an Instrument
  - [ ]  Feature: Instrument connections list and histogram
  - [x]  Feature: Co-authors List

**Comment by kjgarza** [comment]
- [x] the chart doesn't seem to refresh. it stays the same no matter the DOI you input.
- [x] the publications and datasets tables includes other types, it doesn't seem to be filtered
- [x] The table style extends to all tables (add CSS class to the table to avoid that)
- [x] the co authors table is missing the ORCID id
