### ISSUE TITLE
DOD: DOI metadata enrchiment

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#111]
# DOD: DOI metadata enrchiment

### Development Checklist (@jrhoads )
- [ ] Passed through peer review see Pull Request Guidelines
- [ ] Unit, integration, and system tests that all pass on the CI.
- [ ] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [ ] Reviewed by relevant reviewers and all comments are addressed.
- [ ] Confirmed to be working in the stage environment with no new Sentry errors.
- [ ] Write an ADR (when relevant).
- [ ] Confirmed that user stories are met:
  - [ ] Feature 1: Suggested subject-area-classification for repository	
  - [ ] Feature 2: Repository defines its subject-area-classification field	
  - [ ] Feature 3: Access enriched DOI metadata

### Product Engineering Checklist (@kjgarza )
- [x]  Confirmed that user stories are done:
  - [x] Feature 1: Suggested subject-area-classification for repository	
  - [x] Feature 2: Repository defines its subject-area-classification field	
  - [x] Feature 3: Access enriched DOI metadata
- [ ] Feature Flag has been removed. (where relevant)

**Comment by jrhoads** [comment]
Fabrica Branch deployment on Vercel - https://bracco-9yn8nvi0w-datacite.vercel.app/repositories/datacite.test

**Comment by kjgarza** [comment]
https://datacite.sentry.io/issues/3938675692/?environment=stage&project=1410849&query=is%3Aunresolved&referrer=issue-stream

**Comment by kjgarza** [comment]
validation query

```
{
	works(facetCount:50, repositoryId:"datacite.demo") {
		totalCount
		fieldsOfScience {
			id
			count
		}
		fieldsOfScienceCombined {
			id
			count
		}
		fieldsOfScienceRepository {
			id
			count
		}
	}
}

```

**Comment by kjgarza** [comment]
- [x] Error when clearing the repository type discipline https://bracco-hv8y0asth-datacite.vercel.app/repositories/datacite.demo/edit
