### ISSUE TITLE
DOD: FAIR Island Dashboard - Release 2

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#117]
# DOD: FAIR Island Dashboard - Release 2

To complete this DOD, the lead developer that coded the feature must review and validate that every item in the "Development checklist" has been completed and works correctly in a staging or test environment. Note: automated tests are insufficient to tell if a feature works correctly. 
After completing the "Development checklist", the designer must review and validate every item in the "Product Engineering Checklist."

### Development Checklist (@jrhoads @bklaing2 )
- [x] Passed through peer review. See Pull Request Guidelines
- [x] Unit, integration, and system tests all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [ ] Confirmed to be working in the stage environment with no new [Sentry errors](https://datacite.sentry.io/issues/).
- [x] Write an ADR (when relevant).
- [x] Confirmed that user stories are met:
- [x] Feature: Getting all scholarly outputs linked to an organization
    - [x] Scenario: Getting all scholarly outputs linked to an organization when creator.nameIdentifier.affiliationIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when creator.nameIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when contributor.nameIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when contributor.nameIdentifier.affiliation equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to a DMP linked to an organization
- [x] Feature: Top authors and contributors list
    - [x] Scenario: Facet author profile page by co-author
    - [x] Scenario: with ORCIDs in DOI metadata
    - [x] Scenario: with ORCID claim
- [x] Feature: 100% stacked bar chart
    - [x] Background: Displaying missing and other values
    - [x] Scenario: Display aggregated counts even for missing values
    - [x] Scenario: Display aggregated counts for categories that are not in the top 5
    - [x] Scenario: Displaying information about the charts
    - [x] Scenario: Displaying License chart
    - [x] ~~Scenario: Displaying RelatedIdentifier chart~~
    - [x] ~~Scenario: Displaying Identifier chart~~
    - [x] Scenario: Displaying a Chart Insight Text on every chart
    - [x] Scenario: Displaying a Chart Insight Text when the top category is '__missing__' or '__other__'
- [x] ~~Feature: ORCID chart with 100% bar~~
    - [x] ~~Scenario: Displaying NameIdentifier chart~~
- [x] Feature: Visualizations Color palette
    - [x] Scenario: Showing PIDs in a visualization
    - [x] Scenario: Showing ResourceType in a visualization
    - [x] Scenario: Showing License in a visualization

    
### Product Engineering Checklist
- [x]  Confirmed that user stories are done:
- [x] Feature: Getting all scholarly outputs linked to an organization
    - [x] Scenario: Getting all scholarly outputs linked to an organization when creator.nameIdentifier.affiliationIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when creator.nameIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when contributor.nameIdentifier equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to an organization when contributor.nameIdentifier.affiliation equals Organization's ROR-Id
    - [x] Scenario: Getting all scholarly outputs linked to a DMP linked to an organization
- [x] Feature: Top authors and contributors list
    - [x] Scenario: Facet author profile page by co-author
    - [x] Scenario: with ORCIDs in DOI metadata
    - [x] Scenario: with ORCID claim
- [x] Feature: 100% stacked bar chart
    - [x] Background: Displaying missing and other values
    - [x] Scenario: Display aggregated counts even for missing values
    - [x] Scenario: Display aggregated counts for categories that are not in the top 5
    - [x] Scenario: Displaying information about the charts
    - [x] Scenario: Displaying License chart
    - [x] ~~Scenario: Displaying RelatedIdentifier chart~~
    - [x] ~~Scenario: Displaying Identifier chart~~
    - [x] Scenario: Displaying a Chart Insight Text on every chart
    - [x] Scenario: Displaying a Chart Insight Text when the top category is '__missing__' or '__other__'
- [x] ~~Feature: ORCID chart with 100% bar~~
    - [x] ~~Scenario: Displaying NameIdentifier chart~~
- [x] Feature: Visualizations Color palette
    - [x] Scenario: Showing PIDs in a visualization
    - [x] Scenario: Showing ResourceType in a visualization
    - [x] Scenario: Showing License in a visualization
- [x] Feature Flag has been removed. (where relevant)

**Comment by KellyStathis** [comment]
Tasks for after release:
- [x] Documentation updates (@KellyStathis)
- [x] Verify co-author functionality on Person pages (@KellyStathis)
- [x] Check on changes to behaviour described in https://github.com/datacite/datacite/issues/1891 (@KellyStathis )
