### ISSUE TITLE
DoD: Researcher Profile PARSEC Feedback

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#77]
# Definition of Done Checklist

- [x] As a user, I would like the pages for DOI/ORCID/ROR identifiers to load in less than 10 seconds to not leave the page without seeing the results. datacite/lupo#741

- [x] As a user, I would like a filter works box to search the list of resources in a Researcher Profile page so that I can find items.

- [x] Feature: Search on page

  

- [x] Scenario: Filtering related works and citations on individual pages

    Given that a user is a Profile/Organisation/Work Page and the Profile/Organisation/Work has related works or citations
    When the user enters a term in the "Filter works" search box and click the search icon or presses enter
    Then the page should filter related works or citations according to the words entered.

- [x] As a user with works, I expect the profile page (/orcid.org/{orcid}) response time to be under 10 seconds (LCP < 10s for desktop at P90) datacite/lupo#741

- [x] As a product designer, I would like the filter works button element to have an ID (e.g. “filter-works”), so that we can track selection in our analytics platform.

**Comment by kjgarza** [comment]
It seems that there are some issues.

1. [x] Search in page is still working on the Main search box (top) https://commons.stage.datacite.org/orcid.org/0000-0002-7352-517X?query=kristian+garza. Once on the page this search box should default to search in the context of `/doi.org?query=` https://commons.stage.datacite.org/doi.org?query=
2. [x] The "Filter works" search box should be visible if the result is zero results. So users can redo the search or reset it. See this attempt to search for something that doesn't exist in the works list https://commons.stage.datacite.org/orcid.org/0000-0002-7352-517X?query=Covid-19
3. [x] When clicking the "X" icon in the search box, the filter term disappears but the filter is not reset to its clean state and the works are still filtered. It should reset the query to its basic state.
2. [x] Filter works box seems to have a problem with the width when zoomed at 100% of the screen.

![image](https://user-images.githubusercontent.com/1092861/124422604-d3cf2180-dd63-11eb-8065-f99788f73b87.png)




2. [x] Title of the box should read "Filter Works". User feedback during the Product validation stage (Feb '21), showed that users understood better when using the term "filter" rather than "Search".
4. [x] ID for tracking for the clickable Element is still not present

**Comment by mfenner** [comment]
Thank you Kristian. Let me add some initial feedback: 

* `filter` has a special meaning in the context of faceting, it works differently from `query` in Elasticsearch. That is why I used the more general term `search`. 
* you can use class `search-submit-facets`, input name `query-facets` and svg class `fa-search`. If this is not enough for tracking, please let me know what specifically you need (which element, name of id).

**Comment by kjgarza** [comment]
If the Id is called `filter-works` would be fine. I'm trying to avoid using classes in case their changed when styling the component. That's why the ID. The submit button element would be the one with the ID.

Thanks

**Comment by richardhallett** [comment]
Feedback has been incorporated and deployed.
