### ISSUE TITLE
Validation of Support ORCID Search & Link claiming in DataCite Commons

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#86]
# DOD: Support ORCID Search & Link claiming in DataCite Commons

https://github.com/datacite/datacite/issues/1175#issuecomment-977686168

### Development Checklist
- [x] Passed through peer review see Pull Request Guidelines
- [x] Unit, integration, and system tests that all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [x] Confirmed to be working in the stage environment with no new Sentry errors.
- [x] Confirmed that user stories are met:
  - [x] As a logged-in user, I would like to see which DOIs I can claim into my ORCID Record so that I can add those DOIs to my ORCID record [see Senario Claim DOI].
  -  [x] As a logged-in user, I would like to remove my ORCID claims so that if I make a mistake claiming a DOI, I can correct it.
  -  [x] As a logged-in user, I would like to be able to claim DOIs into my ORCID record so that I can improve my ORCID record.
  -  [x] As a user, I would like to claim the process follows a clear defined set of steps and the user gets visual feedback when he clicks the claim button.
 - Detailed
     - [x] Scenario: Claim DOI
        Given that the user is logged-in
          And that the user is in single DOI page
          And that a the DOI on the page is not been claimed by the user himself
         When the user clicks on claim DOI
         Then the "Claim DOI" button should dissapear
          And the label "Updating Claim" should be shown
          And the DOI Claim should be sent to the ORCID profile as author role
          And after a few minutes the label "Remove Claim" should replace the previous label
          And the "Remove Claim" button shall be shown

    - [x] Scenario: Remove DOI Claim
        Given that the user is logged-in
          And that the user is in single DOI page
          And that a the DOI on the page has been claimed by the user himself
         When the user clicks on "Remove Claim"
         Then a pop-up request to confirm whether the user wants to remove the claim
         When the user clicks confirm
         Then the "Remove Claim" button should dissapear
          And the label "Updating Claim" should be shown
          And the request to Remove the Claim should be sent to the ORCID profile
          And after a few minutes the label "Claim DOI" should replace the previous label
          And the "Claim DOI" button shall be shown

   - [x]  Scenario: Claim DOI or Remove DOI Claim attempt with response error
        Given that the user is logged-in
          And that the user is in single DOI page
          And the user clicks on "claim DOI" or "remove claim"
         When the reponse from ORCID Claim is not succesful
         Then the label "Claim Error" should replace the previous label
          And the "Claim DOI" or "Remove Claim" button be removed.

- [x] As a logged user, I would like to have a near-instantaneous response on the success of my claiming or unclaiming actions.
- [x] As a logged user, I would like that the "Updating Claim" status had a lifespan of the order of minutes, so I can continue working without worrying about the state of the Claim.
- [x] As a user, I would like the UI to claim DOIs follow the default Commons style and usability elements.

### Product Engineering Checklist
- [x]  Confirmed that user stories are done:
  - [x] As a logged-in user, I would like to see which DOIs I can claim into my ORCID Record so that I can add those DOIs to my ORCID record [see Senario Claim DOI].
  -  [x] As a logged-in user, I would like to remove my ORCID claims so that if I make a mistake claiming a DOI, I can correct it.
  -  [x] As a logged-in user, I would like to be able to claim DOIs into my ORCID record so that I can improve my ORCID record.
  -  [x] As a user, I would like to claim the process follows a clear defined set of steps and the user gets visual feedback when he clicks the claim button.
- [x] Feature Flag has been removed. (where relevant)

 - Detailed
   - [x] Scenario: Claim DOI
      Given that the user is logged-in
        And that the user is in single DOI page
        And that a the DOI on the page is not been claimed by the user himself
       When the user clicks on claim DOI
       Then the "Claim DOI" button should dissapear
        And the label "Updating Claim" should be shown
        And the DOI Claim should be sent to the ORCID profile as author role
        And after a few minutes the label "Remove Claim" should replace the previous label
        And the "Remove Claim" button shall be shown

  - [x] Scenario: Remove DOI Claim
      Given that the user is logged-in
        And that the user is in single DOI page
        And that a the DOI on the page has been claimed by the user himself
       When the user clicks on "Remove Claim"
       Then a pop-up request to confirm whether the user wants to remove the claim
       When the user clicks confirm
       Then the "Remove Claim" button should dissapear
        And the label "Updating Claim" should be shown
        And the request to Remove the Claim should be sent to the ORCID profile
        And after a few minutes the label "Claim DOI" should replace the previous label
        And the "Claim DOI" button shall be shown

 - [x]  Scenario: Claim DOI or Remove DOI Claim attempt with response error
      Given that the user is logged-in
        And that the user is in single DOI page
        And the user clicks on "claim DOI" or "remove claim"
       When the reponse from ORCID Claim is not succesful
       Then the label "Claim Error" should replace the previous label
        And the "Claim DOI" or "Remove Claim" button be removed.

Non Functional Requirements

- [x] As a logged user, I would like to have a near-instantaneous response on the success of my claiming or unclaiming actions.
- [x] As a logged user, I would like that the "Updating Claim" status had a lifespan of the order of minutes, so I can continue working without worrying about the state of the Claim.
- [x] As a user, I would like the UI to claim DOIs follow the default Commons style and usability elements.

### Engagement Checklist
- [x] Documentation has been updated
- [x] Blogpost/newsletter has been written

**Comment by kjgarza** [comment]
Overall functionality performs well but a few of the implementation stories need to be refined. 

- [x] Please use the "Updating Claim", as in the spec, in place of _"Claim waiting"_.
- [ ] Do not use the state "Deleted Claim".
- [x] Remove display information for _Source_, _Claimed_ (date), and _Claim status_ in the Individual DOI page.
- [x] Follow the flow described in https://www.figma.com/file/XY0mHdFJAqI0WkGAdBo3JJ/ORCID-Claiming?node-id=243%3A1. 

User story 1 requires the use of Event data, which is to be released later In the future as mentioned in [Product spec](https://docs.google.com/document/d/1bp34dSl-twAsBLfZbEj3atl407DpisCMzzbXNlutRp4/edit#) therefore we do not need to complete in this release.

**Comment by richardhallett** [comment]
1. "Updating Claim" does not accurately reflect what is happening, I can change this, but "Claim Waiting" is more explicit because you are waiting for the claim to happen, Updating claim implies that the action is underway but it may not be. Can we consider keeping the waiting language?

2. Delete state reflects a specific action that has taken place, with the change to single button however it will not show because the action possible from this state is Claim again.

3. I have moved to a single label / action button, this however does bring the problem of if it gets stuck in waiting (for some reason) there is no way to trigger a claim again.

**Comment by kjgarza** [comment]
@sarala to carry out the verification you need to use the user [Lieschen Müller](https://sandbox.orcid.org/0000-0002-9897-6305). Its credentials are in 1Pass and the visit Commos in stage https://commons.stage.datacite.org/doi.org?query=COVID-19+2.

**Comment by sarala** [comment]
Overall the functionality works. A couple of things that you may want to consider improving:
- [ ] Reduce the 10 second delay on claiming
- [ ] Remove 'Claim Deleted' state
- [ ] Removing a claim goes through a state 'Claim waiting'. May be rename to 'Claim deleting'

**Comment by richardhallett** [comment]
1. The reducing of delay isn't really feasible due to the design of the backend system, we are waiting for a queue to do things, therefore the delay exists to give it a chance. it does attempt to retry, but every 10 seconds. We'd need to spend some more time refactoring how Orcid claiming works in order to present this differently on the front-end. This is I think outside the scope of this work.

2. See my comment above, but the Claim Deleted state exists because that is what has happened in regard to system. The System maintains a state separate to that of what is happening on orcid. 
Is the concern here showing this state on the listing page? Because I could potentially remove it from there. The individual claim page it is replaced by the "Claim" button reappearing.

3. This also reflects what is happening on system side, the waiting is an action taking place, the action being e.g. creating or deleting.

**Comment by kjgarza** [comment]
All tasks are completed. There are some issues about the flow (ORCID token) but they are out of scope and they should be addressed separately. Docs are in: https://support.datacite.org/docs/orcid-claiming
