### ISSUE TITLE
DoD: Repository search in DataCite Commons 

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#95]
# DOD: Repository search in DataCite Commons 

### Development Checklist
- [x] Passed through peer review see Pull Request Guidelines
- [x] Unit, integration, and system tests that all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [x] Confirmed to be working in the stage environment with no new Sentry errors.
- [x] Confirmed that user stories are met:
- [x] 1. Feature: Repository Search
 - [x] 1.1 Scenario: Searching repository that exist in re3data
 - [x] 1.2 Scenario: Searching repository/client that exist in datacite api under repository/datacenter/clients
- [x] 2. Feature: Filtering Repository Search Results
  - [x] 2.1 Scenario: Filtering by Certificates
  - [x] 2.2 Scenario: Filtering by FAIR Compliance
  - [x] 2.3 Scenario: Filtering by FAIRsFAIRs Compliance
- [x] 3. Feature: Individual Repository Page
  - [x] 3.1 Scenario: Repository Exists
- [x] 3.A Feature: Repository query API
  - [x] 3.A.1.2 Scenario: when the repository is a re3data repository that has a relationship with datacite repository
  - [x]  3.A.1.3 Scenario:  when the query include a local repositoryID 
  - [x] 3.A.1.4 Scenario: when the repository is a datacite repository that has no relationship with a re3data repository
- [x] 4. Feature: Goto Repository button
- [x] 5. Feature: Contact Links
  - [x] 5.1 Scenario: Contacts Exists
  - [x] 5.2 Scenario: Contacts Do not Exists
- [x] 6. Feature: Repository Metrics Display
  - [x] 6.1 Scenario: Metrics exist
  - [x] 6.2 Scenario: Metrics do not exist
- [x] 7. Feature: Dashboard Display
- [x] 8. Feature: Link to related works 
  - [x] 8.1 Scenario: The repository has related works
- [x] 9. Feature: Advise Message
- [x] 10. Feature: FAQ Link
  - [x] 10.1 Scenario: looking more information about the repository search tools
- [x] 11. Feature: Link to repository from DOI page
- [x] #97
- [x] 13. As a Commons user, I expect the repository page response time to be under 5 seconds (LCP < 5 sec for desktop at P90).
- [x] 14. As a product designer, I would like the following html element to have a ID so that we can track selection in our analytics platform.

### Product Engineering Checklist
- [x] 1. Feature: Repository Search
 - [x] 1.1 Scenario: Searching repository that exist in re3data
 - [x] 1.2 Scenario: Searching repository/client that exist in datacite api under repository/datacenter/clients
- [x] 2. Feature: Filtering Repository Search Results
  - [x] 2.1 Scenario: Filtering by Certificates
  - [x] 2.2 Scenario: Filtering by FAIR Compliance
  - [x] 2.3 Scenario: Filtering by FAIRsFAIRs Compliance
- [x] 3. Feature: Individual Repository Page
  - [x] 3.1 Scenario: Repository Exists
- [x] 3.A Feature: Repository query API
  - [x] 3.A.1.2 Scenario: when the repository is a re3data repository that has a relationship with datacite repository
  - [x]  3.A.1.3 Scenario:  when the query include a local repositoryID 
  - [x] 3.A.1.4 Scenario: when the repository is a datacite repository that has no relationship with a re3data repository
- [x] 4. Feature: Goto Repository button
- [x] 5. Feature: Contact Links
  - [x] 5.1 Scenario: Contacts Exists
  - [x] 5.2 Scenario: Contacts Do not Exists
- [x] 6. Feature: Repository Metrics Display
  - [x] 6.1 Scenario: Metrics exist
  - [x] 6.2 Scenario: Metrics do not exist
- [x] 7. Feature: Dashboard Display
- [x] 8. Feature: Link to related works 
  - [x] 8.1 Scenario: The repository has related works
- [x] 9. Feature: Advise Message
- [x] 10. Feature: FAQ Link
  - [x] 10.1 Scenario: looking more information about the repository search tools
- [x] 11. Feature: Link to repository from DOI page
- [ ] 12. ~~Feature: Redirect Search/Repository Finder to Commons~~
- [x] 13. As a Commons user, I expect the repository page response time to be under 5 seconds (LCP < 5 sec for desktop at P90).
- [x] 14. As a product designer, I would like the following html element to have a ID so that we can track selection in our analytics platform.
- [x] Feature Flag has been removed. (where relevant)

### Engagement Checklist
- [x] Documentation has been updated
- [x] Blogpost/newsletter has been written

**Comment by kjgarza** [comment]
Thanks @jrhoads , it looks great. there are a few details but i guess they just need clarification. I include them here and in usersnap.

- [x] 5.2 Scenario: Contacts Do not Exists. Contacts section still appears even when there are no contacts. See https://commons.stage.datacite.org/repositories/q98cd5l
- [x] Feature 3. There seems to be duplicated records in the API response. See https://commons.stage.datacite.org/repositories?query=LMU-ifo+Economics+%26+Business+Data+Center
- [x] Scenario 2.2 Maybe this is just data consistency but the filter only shows 228 hits when in re3data there are 283 https://www.re3data.org/search?query=&dataAccess%5B%5D=open&pidSystems%5B%5D=DOI&subjects%5B%5D=34%20Geosciences%20%28including%20Geography%29
- [x] Scenario 2.3 Maybe this is just data consistency but the filter only shows 677 hits when in re3data there are 803 https://www.re3data.org/search?query=&dataAccess%5B%5D=open&pidSystems%5B%5D=DOI

**Comment by jrhoads** [comment]
Fixed feature 5.2

**Comment by jrhoads** [comment]
Re: Feature 3.

In staging, the client information does not contain the re3dataId.  In production, it does.  In this particular case it will work out just fine in production.

It is conceivable that a client repository in production does not have a re3dataId set even when when one exists in re3Data.
In that case they would show up as separate entries in the repository search in commons.

**Comment by jrhoads** [comment]
Scenario 2.2 and 2.3
I am not sure how re3data runs it's queries on their end.
The current deployment to staging shows numbers similar to repository finder for both of the filters.

**Comment by kjgarza** [comment]
Validation's complete. 

@jrhoads will prepare a separate PR for addressing https://github.com/datacite/tasks/issues/97.
