### ISSUE TITLE
DOD: Improve Prefix Workflow

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#96]
# DOD: Improve Prefix Workflow

### Development Checklist
- [x] Passed through peer review see Pull Request Guidelines
- [x] Unit, integration, and system tests that all pass on the CI.
- [x] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [x] Reviewed by relevant reviewers and all comments are addressed.
- [x] Confirmed to be working in the stage environment with no new Sentry errors.
- [x] Confirmed that user stories are met:
**Feature: Automatic prefix assignation**
- [x] Scenario: Add new repository
**Feature: enable “Add repository” button in the Repositories tab**
- [x] Scenario: there are prefixes available
- [x] Scenario: there are no prefixes available
	

**Feature: show “Assign Prefix” button in the Prefixes tab**
- [x] Scenario: there are prefixes available
- [x] Scenario: Staff wants to assign a prefix
- [x] Scenario: the user is NOT of the staff_admin role

**Feature: available number of prefixes warning**
- [x] Scenario: show available number of prefixes
- [x] Scenario: there are NO prefixes available

### Acceptance Testing Strategy
- [x] Deploy to Vercel, but lower the desired minimum number of free prefixes to a small number (such as 10) so that acceptance testing can be done more easily in all cases (no available prefixes (0), too few available prefixes (< 10), acceptable number of available prefixes (10 or greater).  I added an environment variable that can be used to change this quantity so we can set to to whatever we need.

### Product Engineering Checklist

**Feature: Automatic prefix assignation**
- [x] Scenario: Add new repository
**Feature: enable “Add repository” button in the Repositories tab**
- [x] Scenario: there are prefixes available
- [x] Scenario: there are no prefixes available
	

**Feature: show “Assign Prefix” button in the Prefixes tab**
- [x] Scenario: there are prefixes available
- [x] Scenario: Staff wants to assign a prefix
- [x] Scenario: the user is NOT of the staff_admin role

**Feature: available number of prefixes warning**
- [x] Scenario: show available number of prefixes
- [x] Scenario: there are NO prefixes available

- [ ] Feature Flag has been removed. (where relevant)

### Engagement Checklist
- [x] Documentation has been updated
- [x] Blogpost/newsletter has been written

**Comment by kjgarza** [comment]
- [x] Scenario: show available number of prefixes. The message is visible only on the settings page of the ADMIN but it should be visible in all settings pages even when moving across members. the only condition is that the use is role ADMIN https://bracco-6m0rfpcef-datacite.vercel.app/repositories/ethz.ubasojs .
- [x] Scenario: there are NO prefixes available. The message is visible only on the settings page of the ADMIN but it should be visible in all settings pages even when moving across members.

**Comment by svogt0511** [comment]
> * [x]  Scenario: show available number of prefixes. The message is visible only on the settings page of the ADMIN but it should be visible in all settings pages even when moving across members. the only condition is that the use is role ADMIN https://bracco-6m0rfpcef-datacite.vercel.app/repositories/ethz.ubasojs .

This will be in the next vercel release.

> * [x]  Scenario: there are NO prefixes available. The message is visible only on the settings page of the ADMIN but it should be visible in all settings pages even when moving across members.

This will be in the next vercel release.  Originally it sounded like the requirement was for this message to show 'across all tabs' for a staff_admin.  I will change it as described in the scenario, above.

I will post a link to the vercel deployment when it is ready to go.

**Comment by svogt0511** [comment]
I have deployed a new version of this to vercel, [here](https://bracco-bqamm52ok-datacite.vercel.app/).  It should address the issues above.  Additionally, I have reduced the number where the warning appears so that we can try the test strategy, I added to the checklist, above. 

The link to the vercel deployment:  https://bracco-bqamm52ok-datacite.vercel.app/

@kjgarza and @MaryHirsch please give it a try and let me know what else you find.  

Thanks!

**Comment by kjgarza** [comment]
@paulvierkant And @MaryHirsch could  you please "check" the box about the docs and the blog post, when you are finished with it?  **and maybe provide the link here**

**Comment by MaryHirsch** [comment]
docs are in google: https://docs.google.com/document/d/1BK_-tvx93B2rjO663CgGkJpKzsa6m9a1SIXkfLU2_Rs/edit . We were planning to publish this new section in the existing docs for creating a repository when the new prefix workflow is released into production, we will also send an email communication and share the blog post all at the same time
